Opensource way update
defenseunicorns/Defense-Unicorns-Culture pull request #16
Opened 2022-08-30 17:59 UTC by brandtkeller

Updating value

`Open Source` -> `The Open Source Way`

See - [link](https://opensource.com/open-source-way)

The champions met and agreed upon valuing a principle as opposed to a "thing/action".

I'm a believer in traceability, and want to be able to derive metrics for actions that the advocates are monitoring. As such, I Included queries to be used in slack for purposes of developing metrics and understanding what is/is-not working (let me know if we need to remove this for externally facing relevance).

2022-09-09 15:29 UTC, mikevanhemert approved these changes, later dismissed
Everything reads very cleanly. I especially love that you included metrics in your engagement plan :heart: 

How do you plan on doing the weekly and monthly engagements? Same day weekly (which day?)? Is the monthly recognition a meeting, an email, a post, a video, something else?

2022-09-09 16:04 UTC, brandtkeller commented
> Everything reads very cleanly. I especially love that you included metrics in your engagement plan ❤️
> 
> How do you plan on doing the weekly and monthly engagements? Same day weekly (which day?)? Is the monthly recognition a meeting, an email, a post, a video, something else?

Great questions @mikevanhemert! More clarity would be useful here. I was just talking to the advocates yesterday about choosing a day that would be separate from other values. Having that established in the doc would be great for alignment.

2022-09-20 21:56 UTC, brandtkeller commented
Updating for clarity - want to hash on the Monthly objective for a target that is maintainable and scalable.

2022-09-20 21:57 UTC, mikevanhemert submitted a review, later dismissed
Love it!

2022-09-26 18:15 UTC, Racer159 requested changes
Overall looks good! I think we could look into bots too to queue up the message content.  Only requested some flow improvements to the value intro.

2022-09-26 18:15 UTC, Racer159 commented on README.md
> +Progress and Innovation are spaces that any member of Defense Unicorns can strive towards. It is also a space where we can contribute to the betterment of society through knowledge sharing and teachi
Potential rewording/flow enhancement:

```
Progress and innovation are spaces that any member of Defense Unicorns should strive to expand, contributing to the betterment of society through sharing of knowledge and teaching of others. These others may be fellow Unicorns who are broadening their horizons to new technologies or workflows, but it may also be external with the free sharing of processes, information, data and code building a more free and secure tomorrow for everyone. We share processes in a way that enable people to provide contributions directly and asynchronously - rather than through specified focal or obfuscated synchronous engagements. It also means that we advocate and encourage any member of the company to review and participate in currently established products/processes and enable them to contribute through any iteration that makes the product/process better than it was originally. 
```

2022-09-26 18:30 UTC, brandtkeller commented on README.md
> +Progress and Innovation are spaces that any member of Defense Unicorns can strive towards. It is also a space where we can contribute to the betterment of society through knowledge sharing and teachi
I like the update - revised!

2022-09-26 18:36 UTC, Racer159 approved these changes
lgtm!

2022-09-26 18:52 UTC, merged